name: Package Plugin

on:
  release:
    types:
      - published
      - edited

permissions:
  contents: write

jobs:
  deploy:
    name: On Release
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v5

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          coverage: none
          tools: composer:v2

      - name: Validate composer.json
        run: composer validate

      - name: Prepare files
        run: |
          mkdir -p "${RUNNER_TEMP}/dist/${PACKAGE}"
          rsync -r --exclude-from=.distignore . "${RUNNER_TEMP}/dist/${PACKAGE}"
          find "${RUNNER_TEMP}/dist"
        env:
          PACKAGE: ${{ github.event.repository.name }}

      - name: Create zip
        working-directory: ${{ runner.temp }}/dist
        run: zip -r "${PACKAGE}.zip" "${PACKAGE}"
        env:
          PACKAGE: ${{ github.event.repository.name }}

      - name: Upload release asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PACKAGE: ${{ github.event.repository.name }}
          TAG: ${{ github.event.release.tag_name }}
        run: gh release upload "$TAG" "${RUNNER_TEMP}/dist/${PACKAGE}.zip" --clobber
